apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: non-front-end-api-allow
  namespace: propdevelopment
spec:
  podSelector:
    matchLabels:
      role: front-end
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: front-end-app

  egress:
    - to:
      - podSelector:
          matchLabels:
            role: admin-front-end
